receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 1s

exporters:
  logging:
    verbosity: detailed
  awsxray:
  datadog:
    api:
      key: ${env:DD_API_KEY}

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - awsxray
        - logging
        - datadog
    metrics:
      receivers:
        - otlp
      exporters:
        - logging
  telemetry:
    metrics:
      address: localhost:8888
